/* MAXRENTAL catalogue.
   Mirrors the shape of the reference site's mock/productList.js. Every entry
   here is a real product from maxrental.my — names, specs and prices are the
   live ones as of 23 Sep 2026. */

window.CATEGORIES = [
    { slug: 'short-term', label: 'Short Term Rental' },
    { slug: 'long-term', label: 'Long Term Rental' },
    { slug: 'new-laptop', label: 'Brand New Laptop' },
    { slug: 'new-desktop', label: 'Brand New Desktop' },
    { slug: 'ref-laptop', label: 'Refurbished Laptop' },
    { slug: 'ref-desktop', label: 'Refurbished Desktop' },
    { slug: 'others', label: 'Others' },
];

/* tile  = 0.749 portrait grid image   (img/tiles/<key>-a|b.jpg)
   thumb = 1:1 cart + footer thumbnail (img/thumbs/<key>.jpg)       */

window.PRODUCTS = [
    /* ---------------------------------------------- short term rental --- */
    {
        key: 'desktop-rental-monthly-plan-basic',
        collection: 'short-term',
        model: 'BASIC',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN BASIC',
        price: 'RM100 / month',
        value: 100,
        unit: 'month',
        spec: 'Intel i5-6th Gen, 8GB RAM, 128GB SSD, Win10 Pro, 22 inch Monitor',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'desktop-rental-monthly-plan-mid-range',
        collection: 'short-term',
        model: 'MID',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN MID RANGE',
        price: 'RM140 / month',
        value: 140,
        unit: 'month',
        spec: 'Intel i5-8th Gen, 16GB RAM, 256GB SSD, Win11 Pro, 22 inch Monitor',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'desktop-rental-monthly-plan-advanced',
        collection: 'short-term',
        model: 'ADV',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN ADVANCED',
        price: 'RM180 / month',
        value: 180,
        unit: 'month',
        spec: 'Intel i7-8th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 22 inch Monitor',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'laptop-rental-monthly-plan-basic',
        collection: 'short-term',
        model: 'BASIC',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN BASIC',
        price: 'RM100 / month',
        value: 100,
        unit: 'month',
        spec: 'Intel i5-6th Gen, 8GB RAM, 128GB SSD, Win10 Pro, 14 inch Display',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'laptop-rental-monthly-plan-mid-range',
        collection: 'short-term',
        model: 'MID',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN MID RANGE',
        price: 'RM140 / month',
        value: 140,
        unit: 'month',
        spec: 'Intel i5-8th Gen, 16GB RAM, 256GB SSD, Win11 Pro, 14 inch Display',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'laptop-rental-monthly-plan-advanced',
        collection: 'short-term',
        model: 'ADV',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN ADVANCED',
        price: 'RM180 / month',
        value: 180,
        unit: 'month',
        spec: 'Intel i7-8th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 14 inch Display',
        terms: '1 / 3 / 6 / 9 / 12 months',
    },
    {
        key: 'apple-macbook-air-m2-short-rental-plan',
        collection: 'short-term',
        model: 'M2',
        family: 'MACBOOK AIR',
        name: 'MACBOOK AIR M2',
        price: 'RM300 / month',
        value: 300,
        unit: 'month',
        spec: 'Apple M2 Chip, 8GB RAM, 256GB SSD, 13/15 inch Display, macOS',
        terms: '1 / 3 / 6 / 9 / 12 months',
        note: 'Refundable deposit of RM2,000.00',
    },

    /* ----------------------------------------------- long term rental --- */
    {
        key: 'desktop-rental-plan',
        collection: 'long-term',
        model: 'BASIC',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN BASIC',
        price: 'RM50 / month',
        value: 50,
        unit: 'month',
        spec: 'Intel i5-6th Gen, 8GB RAM, 128GB SSD, Win10 Pro, 22 inch Monitor',
        terms: '24 / 36 months',
    },
    {
        key: 'desktop-rental-monthly-plan-mid-range-2',
        collection: 'long-term',
        model: 'MID',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN MID RANGE',
        price: 'RM70 / month',
        value: 70,
        unit: 'month',
        spec: 'Intel i5-8th Gen, 16GB RAM, 256GB SSD, Win11 Pro, 22 inch Monitor',
        terms: '24 / 36 months',
    },
    {
        key: 'desktop-rental-monthly-plan-advanced-2',
        collection: 'long-term',
        model: 'ADV',
        family: 'DESKTOP PLAN',
        name: 'DESKTOP PLAN ADVANCED',
        price: 'RM90 / month',
        value: 90,
        unit: 'month',
        spec: 'Intel i7-8th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 22 inch Monitor',
        terms: '24 / 36 months',
    },
    {
        key: 'laptop-rental-monthly-plan-basic-2',
        collection: 'long-term',
        model: 'BASIC',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN BASIC',
        price: 'RM50 / month',
        value: 50,
        unit: 'month',
        spec: 'Intel i5-6th Gen, 8GB RAM, 128GB SSD, Win10 Pro, 14 inch Display',
        terms: '24 / 36 months',
    },
    {
        key: 'laptop-rental-monthly-plan-mid-range-2',
        collection: 'long-term',
        model: 'MID',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN MID RANGE',
        price: 'RM70 / month',
        value: 70,
        unit: 'month',
        spec: 'Intel i5-8th Gen, 16GB RAM, 256GB SSD, Win11 Pro, 14 inch Display',
        terms: '24 / 36 months',
    },
    {
        key: 'laptop-rental-monthly-plan-advanced-2',
        collection: 'long-term',
        model: 'ADV',
        family: 'LAPTOP PLAN',
        name: 'LAPTOP PLAN ADVANCED',
        price: 'RM90 / month',
        value: 90,
        unit: 'month',
        spec: 'Intel i7-8th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 14 inch Display',
        terms: '24 / 36 months',
    },
    {
        key: 'laptop-rental-plan-macbook',
        collection: 'long-term',
        model: 'M2',
        family: 'MACBOOK AIR',
        name: 'MACBOOK AIR M2',
        price: 'RM150 / month',
        value: 150,
        unit: 'month',
        spec: 'Apple M2 Chip, 8GB RAM, 256GB SSD, 13/15 inch Display, macOS',
        terms: '24 months RM220 / 36 months RM150',
        note: 'Refundable deposit of RM2,000.00',
    },

    /* -------------------------------------------------- brand new -------- */
    {
        key: 'hp-probook-440-g10-laptop',
        collection: 'new-laptop',
        model: 'G10',
        family: 'HP PROBOOK 440',
        name: 'HP PROBOOK 440 G10',
        price: 'RM3,500.00',
        was: 'RM4,000.00',
        value: 3500,
        spec: 'Intel i5-13th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 14 inch',
        warranty: '3 Years Warranty',
    },
    {
        key: 'dell-latitude-3450-laptop',
        collection: 'new-laptop',
        model: '3450',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 3450',
        price: 'RM3,500.00',
        was: 'RM4,000.00',
        value: 3500,
        spec: 'Intel i5-13th Gen, 16GB RAM, 512GB SSD, Win11 Pro, 14 inch',
        warranty: '3 Years Warranty',
    },
    {
        key: 'dell-dc-15250-laptop',
        collection: 'new-laptop',
        model: '15250',
        family: 'DELL DC',
        name: 'DELL DC 15250',
        price: 'RM2,500.00',
        was: 'RM3,000.00',
        value: 2500,
        spec: 'Intel i5, 16GB RAM, 512GB SSD, Win11 Pro, 15 inch',
        warranty: '1 Year Warranty',
    },

    /* --------------------------------------------- refurbished laptop ---- */
    {
        key: 'hp-zbook-14-g7-laptop',
        collection: 'ref-laptop',
        model: 'G7',
        family: 'HP ZBOOK 14',
        name: 'HP ZBOOK 14 G7',
        price: 'RM2,000.00',
        value: 2000,
        spec: 'Intel i7, 16GB RAM, 512GB SSD, Win11 Pro, 14 inch',
    },
    {
        key: 'hp-probook-450-g7-laptop',
        collection: 'ref-laptop',
        model: 'G7',
        family: 'HP PROBOOK 450',
        name: 'HP PROBOOK 450 G7',
        price: 'RM1,900.00',
        value: 1900,
        spec: 'Intel i5, 16GB RAM, 256GB SSD, Win11 Pro, 15 inch',
    },
    {
        key: 'hp-probook-440-g8-laptop',
        collection: 'ref-laptop',
        model: 'G8',
        family: 'HP PROBOOK 440',
        name: 'HP PROBOOK 440 G8',
        price: 'RM1,900.00',
        value: 1900,
        spec: 'Intel i5, 16GB RAM, 256GB SSD, Win11 Pro, 14 inch',
    },
    {
        key: 'dell-latitude-5420-laptop',
        collection: 'ref-laptop',
        model: '5420',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 5420',
        price: 'RM1,900.00',
        value: 1900,
        spec: 'Intel i5, 16GB RAM, 256GB SSD, Win11 Pro, 14 inch',
    },
    {
        key: 'dell-latitude-5400-laptop',
        collection: 'ref-laptop',
        model: '5400',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 5400',
        price: 'RM1,500.00',
        value: 1500,
        spec: 'Intel i5, 8GB RAM, 256GB SSD, Win10 Pro, 14 inch',
    },
    {
        key: 'dell-latitude-3400-laptop',
        collection: 'ref-laptop',
        model: '3400',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 3400',
        price: 'RM1,300.00',
        value: 1300,
        spec: 'Intel i5, 8GB RAM, 256GB SSD, Win10 Pro, 14 inch',
    },
    {
        key: 'dell-latitude-5490-laptop',
        collection: 'ref-laptop',
        model: '5490',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 5490',
        price: 'RM1,200.00',
        value: 1200,
        spec: 'Intel i5, 8GB RAM, 256GB SSD, Win10 Pro, 14 inch',
    },
    {
        key: 'dell-latitude-5470-laptop',
        collection: 'ref-laptop',
        model: '5470',
        family: 'DELL LATITUDE',
        name: 'DELL LATITUDE 5470',
        price: 'RM1,000.00',
        value: 1000,
        spec: 'Intel i5, 8GB RAM, 128GB SSD, Win10 Pro, 14 inch',
    },
    {
        key: 'lenovo-l380-laptop',
        collection: 'ref-laptop',
        model: 'L380',
        family: 'LENOVO THINKPAD',
        name: 'LENOVO L380',
        price: 'RM700.00',
        value: 700,
        spec: 'Intel i5, 8GB RAM, 128GB SSD, Win10 Pro, 13 inch',
    },

    /* -------------------------------------------- refurbished desktop ---- */
    {
        key: 'dell-optiplex-5080sff-desktop',
        collection: 'ref-desktop',
        model: '5080',
        family: 'DELL OPTIPLEX',
        name: 'DELL OPTIPLEX 5080 SFF',
        price: 'RM2,000.00',
        value: 2000,
        spec: 'Intel i7, 16GB RAM, 512GB SSD, Win11 Pro, Small Form Factor',
    },
    {
        key: 'dell-optiplex-3060-desktop',
        collection: 'ref-desktop',
        model: '3060',
        family: 'DELL OPTIPLEX',
        name: 'DELL OPTIPLEX 3060',
        price: 'RM1,500.00',
        value: 1500,
        spec: 'Intel i5, 8GB RAM, 256GB SSD, Win10 Pro, Tower',
    },
    {
        key: 'hp-elitedesk-800-g3-desktop',
        collection: 'ref-desktop',
        model: 'G3',
        family: 'HP ELITEDESK 800',
        name: 'HP ELITEDESK 800 G3',
        price: 'RM900.00',
        was: 'RM1,400.00',
        value: 900,
        spec: 'Intel i5, 8GB RAM, 256GB SSD, Win10 Pro, Small Form Factor',
    },

    /* ------------------------------------------------------------ others -- */
    {
        key: 'microsoft-office-home-business-2024',
        collection: 'others',
        model: '2024',
        family: 'MS OFFICE',
        name: 'MICROSOFT OFFICE H&B 2024',
        price: 'RM954.00',
        was: 'RM1,000.00',
        value: 954,
        spec: 'Word, Excel, PowerPoint, Outlook. Genuine e-licence, Windows 10/11',
    },
];

/* image paths are derived from the key so the data stays terse */
window.PRODUCTS.forEach(function (p) {
    p.img = 'img/tiles/' + p.key + '-a.jpg';
    p.imgH = 'img/tiles/' + p.key + '-b.jpg';
    p.thumb = 'img/thumbs/' + p.key + '.jpg';
    p.url = 'product.html?collection=' + p.collection + '&model=' + p.key;
});
